name: yBuff
version: '1.0.1'
main: com.ylabui.yBuff.Main
api-version: '1.21'
authors: [ yLabui ]
description: Manage the buff commands
website: https://github.com/ylabui
commands:
  buff:
    description: Use to manage buff